<?php /** @var $this Api2cart_Bridge_Block_Adminhtml_System_Config_Block */ ?>
<div class="section-config active">
    <div class="entry-edit-head collapseable">
        <a id="bridge_general-head"
           href="#"
           onclick="Fieldset.toggleCollapse('bridge_general'); return false;"
           class="open"><?php echo $this->__('General') ?></a>
    </div>

    <input id="bridge_general-state" name="config_state[bridge_general]" type="hidden" value="1">
    <div id="bridge_general">
        <script>
            var baseUrl = '<?php echo Mage::getBaseUrl();?>';
            var ajaxUrl = '<?php echo Mage::getUrl('adminhtml/api2cart/'); ?>';
            var storeKey = '<?php echo ($key = $this->storeKey()) ? $key : ''?>';
        </script>
        <div style="position: relative;">
            <div class="message">dsa</div>
            <div class="text-center">
                <a class="bridge_logo" target="_blank" href="https://www.api2cart.com">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>adminhtml/default/default/api2cart_bidge/logo.png" alt="API2Cart - Unified Shopping Cart API Integration Interface">
                </a>
            </div>
        </div>
        <div class="text-center">
            <p>API2Cart is a unified platform to integrate with 30+ shopping carts including Magento, Shopify, WooCommerce, Bigcommerce, OpenCart, VirtueMart and others. It makes it easy to retrieve, add, delete, update, and synchronize such store data as customers, orders, products, and categories to provide different B2B services.</p>
        </div>
        <div class="container" style="display:none;">
            <div class="uninstalled text-center">
                <p id="connector-installed-txt">The connector will be installed automatically. Just click the button below and have the connection between your <?php //echo $cartName; ?> store and the system needed established.</p>
                <button type="button" class="btn-connect btn-setup connect">Connect</button>
            </div>

            <div class="installed">
                <div class="text">
                    <b>Congratulations! The plugin is installed!</b><br><br>
                    <ul class="list-create-account">
                        <li>To complete the connection process, follow the few steps listed below:</li>
                        <li>1) Create an API2Cart account.</li>
                        <li>2) Add your store to the store panel by indicating its URL and cart type.</li>
                        <li>3) Voila! The connection between your store and API2Cart is established!</li>
                    </ul>
                    <br>
                    <b>Please note.</b> Store data interaction only works if you are integrated with the service.
                    It allows to get, synchronize, and manipulate various information on customers, products, categories, and orders from the stores added to the directory.
                    For more information, schedule a call with our representative and have the details explained to you.
                    <br>
                </div>
                <div class="store-key text-center">
                    <span class="store-key-title">Your store key:</span>
                    <span class="store-key-content"></span>
                    <button type="button" id="updateBridgeStoreKey" class="btn-update-store-key update">Update Store Key</button>
                </div>
                <div class="text-center">
                    <button type="button" class="btn-disconnect btn-setup disconnect">Disconnect</button>
                </div>
            </div>
        </div>

        <div class="loader text-center" style="display: none;">
            <div class="progress progress-dark progress-small progress-striped active">
                <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
    </div>
</div>